CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT UNIQUE,
password TEXT,
role TEXT CHECK(role IN ('admin','cashier','manager')) DEFAULT 'cashier',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);