CREATE TABLE IF NOT EXISTS product_clothing (
id INTEGER PRIMARY KEY AUTOINCREMENT,
product_id INTEGER UNIQUE NOT NULL,
size TEXT,
color TEXT,
brand TEXT,
material TEXT,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);