CREATE TABLE IF NOT EXISTS product_food (
id INTEGER PRIMARY KEY AUTOINCREMENT,
product_id INTEGER UNIQUE NOT NULL,
recipe TEXT,
ingredients TEXT,
kitchen_required INTEGER DEFAULT 1,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);